# curl GET http://localhost:8080/api/v1/provisioning/1a-2b-3c-4d-5e-6f
#'--- Conference phone with override fragment ---'
GET http://localhost:8080/api/v1/provisioning/1a-2b-3c-4d-5e-6f

###

# curl GET http://localhost:8080/api/v1/provisioning/a1-b2-c3-d4-e5-f6
#'--- Desk phone with override fragment ---'
GET http://localhost:8080/api/v1/provisioning/a1-b2-c3-d4-e5-f6

###

# curl GET http://localhost:8080/api/v1/provisioning/f1-e2-d3-c4-b5-a6
#'--- Conference phone without override fragment ---'
GET http://localhost:8080/api/v1/provisioning/f1-e2-d3-c4-b5-a6

###

# curl GET http://localhost:8080/api/v1/provisioning/aa-bb-cc-dd-ee-ff
#'--- Desk phone without override fragment ---'
GET http://localhost:8080/api/v1/provisioning/aa-bb-cc-dd-ee-ff

###
